# This is a basic workflow to help you get started with Actions

name: Upgrade AKS cluster

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 7 3 10 *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upgrade-cluster:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: Upgrade AKS cluster
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az aks upgrade -g akstest -n aks01 --kubernetes-version 1.20.9 -y
